#!/usr/bin/env bash

set -e

gemfury_push_token="$1"
branch="$2"
package_name="$3"
package_version="$4"
circle_build_num="$5"

if [[ $branch == "main" ]]; then
    # create dist using python setup dist
    python3 setup.py sdist
    # push dist to gemfury using curl and token
    curl -F package=@dist/$package_name-$package_version.tar.gz https://$gemfury_push_token@push.fury.io/themuse
else
    # Changes the version number inside setup.py to be a temporary build based on circleci build number
    sed -i -e 's/VERSION = "'$package_version'"/VERSION = "'$package_version'+build-'$branch'"/g' setup.py
    # create dist using python setup dist
    python3 setup.py sdist
    # push dist to gemfury using curl and token
    curl -F package=@dist/$package_name-$package_version+build-$branch.tar.gz https://$gemfury_push_token@push.fury.io/themuse
fi
